
move_command: 2
# 0:stop 1:easy_stop 2:move
states : 4
# 3:null 4:move_pp 5:move_mpc 6:move_pp_mpc
plot : 8
# 7: no_plotting 8:plotting
map: 10
# 9:no_map 10:not_complete 11:complete
state_estimation: 13
# 12:not_ready 13:ready
system_diagnostic: 15
# 14:not_finished 15:finished

v_kin_max : 4
v_dyn_min : 5

ld_curvature_min: 5
#curvature min
ld_curvature_max: 50
#curvature max
#	0:v_kin_max "range of v in kinematic region"		v_dun_mian:v_ul "range of v in dynamic region"

x_pos: 0
y_pos: 0
theta: 0
v_x: 0
v_y: 0
r    : 0          
s: 0
delta: 0
d       : 0      
v_s: 0
v_delta: 0
v_d : 0
a_s: 0
a_delta: 0
a_d: 0
                  
x_pos_ub: 30
y_pos_ub: 30
theta_ub: 30
v_x_ub: 5
v_y_ub: 30
r_ub  : 1.0
s_ub: 30
delta_ub: 100.5
d_ub: 30
v_s_ub: 30
v_delta_ub: 30
v_d_ub: 30
a_s_ub: 30
a_delta_ub: 30
a_d_ub: 30

x_pos_lb: -30
y_pos_lb: -30
theta_lb: -30
v_x_lb: -30
v_y_lb: -30
r_lb: -1.0
s_lb: -30
delta_lb: -100.5
d_lb: -30
v_s_lb: -30
v_delta_lb: -30
v_d_lb: -30
a_s_lb: -30
a_delta_lb: -30
a_d_lb: -30

ld_1: 4
ld_2 : 5
ld_3: 5.5
ld_4: 6.5

pos_tol: 0.1

v_des: 0
v_des_lb: 3.0
v_des_ub: 20.0
t_max: 0
traction_b: 1.0

l: 2.10 #1.53313
l_f: 0.5
l_r: 0.5
i_z: 1.0
car_mass: 131

first_transform_m_rbl_x : -8.36665258
#first transform from map_frame to rare base_link frame
first_transform_m_rbl_y : 10.88822546
#first transform from map_frame to rare base_link frame
first_transform_m_rbl_z : 0
#first transform from map_frame to rare base_link frame
first_transform_m_rbl_theta : 0.0
#first transform from map_frame to rare base_link frame


#######################################################################3
###################################################################
mode_stop : 1
mode_easy_stop : 0
mode_move : 0
mode_move_pp : 0
mode_move_mpc : 0
mode_move_pp_mpc : 0
mode_plot : 0


full_map : 0

first_transform_x : 0
first_transform_y : 0
first_transform_z : 0
first_transform_theta : 0

pp_const_vel : 1
pp_vel_setpoint : 5.0
pp_lookahead : 2
pp_lookahead_2 : 4

ub_x : 30
ub_y : 30
ub_theta : 30
ub_vx : 30
ub_vy : 30
ub_r : 30
ub_s : 30
ub_delta : 30

ub_throttel : 30
ub_vs : 30
ub_vdelta : 30


lb_x : 30
lb_y : 30
lb_theta : 30
lb_vx : 30
lb_vy : 30
lb_r : 30
lb_s : 30
lb_delta : 30

lb_throttel : 30
lb_vs : 30
lb_vdelta : 30


